name: only-tests
on:
    push:
        branches:
        - master
        - develop
    pull_request:
        branches:
        - master
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v2
          - name: setup-java
            uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: 'adopt'
          - name: setup-graddle
            uses: eskatos/gradle-command-action@v1
            with:
                arguments: wrapper

          - name: Alls tests and Coverage Checks
            run: ./gradlew clean install
